"""Phase 1.2: look inside the SVG2 annotation parquets (no masks, no videos needed).

Writes a Markdown report (default notes/phase1_inspect.md) with one summary table
comparing every split, then per-split details: top labels, relation types, and one
example video. The terminal only shows progress.

    python tools/inspect_annotations.py                    # every split
    python tools/inspect_annotations.py --only SVG2_test   # splits whose path contains all given words

Open the report in VS Code with Ctrl+Shift+V (Markdown preview).
"""
import argparse
import glob
import json
import os
import time
from collections import Counter

import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq

ROOT = "data/SVG2/data"


def parse(value):
    """Columns hold JSON strings; tolerate already-decoded values and nulls."""
    if value is None:
        return []
    if isinstance(value, str):
        return json.loads(value) if value else []
    return value


def q(values, p):
    return float(np.percentile(np.asarray(values, dtype=float), p)) if values else float("nan")


def summarize(folder):
    files = sorted(glob.glob(os.path.join(folder, "*.parquet")))
    table = pa.concat_tables([pq.read_table(f) for f in files])
    cols = table.column_names

    objs_per_video, attrs_per_obj, rels_per_video = [], [], []
    rel_types, levels, labels = Counter(), Counter(), Counter()
    span_ends, span_lengths = [], []
    frac_endpoints = total_endpoints = zero_len = 0
    camera_rels = uncertain = 0

    for o_raw, r_raw in zip(table.column("objects").to_pylist(), table.column("relationships").to_pylist()):
        objs, rels = parse(o_raw), parse(r_raw)
        objs_per_video.append(len(objs))
        rels_per_video.append(len(rels))
        for ob in objs:
            key = next((k for k in ob if k.startswith("object")), None)
            label = str(ob[key]) if key else "<no object key>"
            labels[label] += 1
            uncertain += "uncertain" in label
            attrs_per_obj.append(len(ob.get("attributes") or []))
            if "level" in ob:
                levels[ob["level"]] += 1
        for rel in rels:
            rel_types[rel[4] if len(rel) > 4 else "<no type field>"] += 1
            camera_rels += -1 in (rel[0], rel[2])
            for s, e in (rel[3] if len(rel) > 3 else []):
                span_ends.append(e)
                span_lengths.append(e - s)
                zero_len += e == s
                total_endpoints += 2
                frac_endpoints += (float(s) != int(s)) + (float(e) != int(e))

    example = {c: table.column(c)[0].as_py() for c in cols}
    return {
        "name": os.path.relpath(folder, ROOT),
        "files": len(files),
        "columns": cols,
        "sources": dict(Counter(table.column("source").to_pylist())) if "source" in cols else {},
        "videos": table.num_rows,
        "objects": sum(objs_per_video),
        "obj_p50": q(objs_per_video, 50), "obj_p90": q(objs_per_video, 90), "obj_max": q(objs_per_video, 100),
        "attrs": sum(attrs_per_obj),
        "attr_p50": q(attrs_per_obj, 50), "attr_p90": q(attrs_per_obj, 90),
        "objs_no_attr": sum(a == 0 for a in attrs_per_obj),
        "rels": sum(rels_per_video),
        "rel_p50": q(rels_per_video, 50), "rel_p90": q(rels_per_video, 90),
        "camera_rels": camera_rels,
        "rel_types": rel_types,
        "levels": levels,
        "labels": labels,
        "uncertain": uncertain,
        "span_end_p50": q(span_ends, 50), "span_end_max": q(span_ends, 100),
        "span_len_p50": q(span_lengths, 50),
        "zero_len": zero_len,
        "frac_pct": 100.0 * frac_endpoints / total_endpoints if total_endpoints else float("nan"),
        "example": example,
    }


def fmt(x, nd=1):
    return "–" if x != x else (f"{x:.{nd}f}" if isinstance(x, float) else str(x))


def write_report(stats, path):
    lines = ["# Phase 1.2: SVG2 annotation inspection", "",
             "Generated by `tools/inspect_annotations.py`. Spans are in seconds.", "",
             "## Summary", "",
             "| split | videos | objects | obj/video p50 (p90, max) | attrs/obj p50 (p90) | objs w/o attrs "
             "| relations | rel/video p50 (p90) | camera rels | distinct labels | 'uncertain' labels "
             "| span end p50 (max) | span len p50 | zero-len spans | fractional endpoints |",
             "|" + "---|" * 15]
    for s in stats:
        lines.append(
            f"| {s['name']} | {s['videos']} | {s['objects']} "
            f"| {fmt(s['obj_p50'])} ({fmt(s['obj_p90'])}, {fmt(s['obj_max'], 0)}) "
            f"| {fmt(s['attr_p50'])} ({fmt(s['attr_p90'])}) | {s['objs_no_attr']} "
            f"| {s['rels']} | {fmt(s['rel_p50'])} ({fmt(s['rel_p90'])}) | {s['camera_rels']} "
            f"| {len(s['labels'])} | {s['uncertain']} "
            f"| {fmt(s['span_end_p50'])} ({fmt(s['span_end_max'])}) | {fmt(s['span_len_p50'])} "
            f"| {s['zero_len']} | {fmt(s['frac_pct'])}% |")

    for s in stats:
        lines += ["", f"## {s['name']}", "",
                  f"- parquet files: {s['files']}; columns: `{s['columns']}`",
                  f"- sources: {s['sources']}"]
        if s["levels"]:
            lines.append(f"- object levels: {dict(s['levels'])}")
        if s["rel_types"]:
            lines.append(f"- relation types: {dict(s['rel_types'].most_common())}")
        lines.append(f"- top 25 labels: {s['labels'].most_common(25)}")
        ex = s["example"]
        lines += ["", f"Example video `{ex.get('video_id')}`:", "", "```"]
        for c in ("objects", "relationships"):
            items = parse(ex.get(c))
            lines.append(f"{c}: {len(items)} items")
            lines += ["  " + json.dumps(it, ensure_ascii=False, default=str)[:300] for it in items[:6]]
            if len(items) > 6:
                lines.append("  ...")
        lines.append("```")

    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", nargs="*", default=[], help="only splits whose path contains all of these words")
    ap.add_argument("--out", default="notes/phase1_inspect.md")
    args = ap.parse_args()

    folders = sorted({os.path.dirname(p) for p in glob.glob(os.path.join(ROOT, "**", "*.parquet"), recursive=True)})
    folders = [f for f in folders if all(w in f for w in args.only)]
    if not folders:
        raise SystemExit(f"No parquet files under {ROOT}. Download data/* first.")

    stats = []
    for f in folders:
        t0 = time.time()
        stats.append(summarize(f))
        print(f"done {os.path.relpath(f, ROOT):35s} {stats[-1]['videos']:8d} videos  ({time.time() - t0:.1f}s)")
    write_report(stats, args.out)
    print(f"\nReport written to {args.out}  (open it in VS Code, Ctrl+Shift+V for preview)")


if __name__ == "__main__":
    main()
