"""Phase 1.4: video length vs. relation time spans, from mask metadata only.

The mask parquets are huge (40 GB for SA-V, 198 GB for PVD) because of the `counts` column
(the RLE strings). Their other columns - video_id, num_frames, mask_height, mask_width,
num_objects - are tiny. This script reads only those columns, straight from the Hugging
Face Hub (range requests; nothing large is downloaded), caches them under
data/SVG2/mask_meta/, joins them with the annotation spans, and writes
notes/phase1_durations.md.

Questions answered:
  - How long are the videos (frames, and seconds where the fps is known)? Compare with paper Table 8.
  - Do relation spans ever end after the video ends? (span units, plot hole P14)
  - Do annotation object ids fit inside the mask files (id < num_objects)?

    python tools/mask_meta.py                  # default splits, PVD limited to --pvd_files shards
    python tools/mask_meta.py --pvd_files 550  # all PVD shards (slower)
"""
import argparse
import glob
import json
import os
import time

import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq

REPO = "datasets/UWGZQ/Synthetic_Visual_Genome2"
DATA_ROOT = "data/SVG2/data"
LOCAL_MASKS = "data/SVG2/masks"
CACHE = "data/SVG2/mask_meta"
META_COLS = ["video_id", "num_frames", "mask_height", "mask_width", "num_objects"]

SPLITS = ["SVG2_test/sav", "SVG2_test/vipseg",
          "academic_datasets/vipseg", "academic_datasets/lvvis", "academic_datasets/ovis",
          "academic_datasets/vidvrd", "academic_datasets/vidor",
          "cleaned/sav", "cleaned/pvd"]

# Frame rate of the frames the masks are indexed by: native rate for SA-V (dataset card:
# 24 fps), the re-encoding rate for the frame-folder datasets (docs/DATA.md). VidOR,
# ImageNet-VidVRD and PVD keep their native, per-video rate, which we do not know here.
KNOWN_FPS = {"SVG2_test/sav": 24, "SVG2_test/vipseg": 6, "cleaned/sav": 24,
             "academic_datasets/vipseg": 6, "academic_datasets/lvvis": 5, "academic_datasets/ovis": 5}


def mask_files(split, max_files, fs):
    local = sorted(glob.glob(os.path.join(LOCAL_MASKS, split, "*.parquet")))
    if local:
        return [(p, None) for p in local[:max_files]]
    remote = sorted(fs.glob(f"{REPO}/masks/{split}/*.parquet"))
    return [(p, fs) for p in remote[:max_files]]


def read_meta(path, fs):
    if fs is None:
        return pq.read_table(path, columns=META_COLS)
    # Small block size: only the footer and the small column chunks are fetched.
    with fs.open(path, "rb", block_size=1 << 20) as f:
        return pq.ParquetFile(f, pre_buffer=False).read(columns=META_COLS)


def load_meta(split, max_files):
    os.makedirs(CACHE, exist_ok=True)
    cache = os.path.join(CACHE, split.replace("/", "__") + f"__{max_files}.parquet")
    if os.path.exists(cache):
        return pq.read_table(cache)
    fs = None
    if not glob.glob(os.path.join(LOCAL_MASKS, split, "*.parquet")):
        from huggingface_hub import HfFileSystem
        fs = HfFileSystem()
    tables = []
    files = mask_files(split, max_files, fs)
    for i, (p, fsi) in enumerate(files):
        tables.append(read_meta(p, fsi))
        print(f"  {split}: {i + 1}/{len(files)} mask files", end="\r", flush=True)
    print()
    table = pa.concat_tables(tables)
    pq.write_table(table, cache)
    return table


def parse(value):
    if value is None:
        return []
    return json.loads(value) if isinstance(value, str) else value


def annotation_info(split):
    """video_id -> (max span end, number of annotated objects, max object id)."""
    info = {}
    for f in sorted(glob.glob(os.path.join(DATA_ROOT, split, "*.parquet"))):
        d = pq.read_table(f, columns=["video_id", "objects", "relationships"]).to_pydict()
        for vid, o, r in zip(d["video_id"], d["objects"], d["relationships"]):
            objs, rels = parse(o), parse(r)
            ends = [e for rel in rels if len(rel) > 3 for _, e in rel[3]]
            ids = [int(k.split("_")[1]) for ob in objs for k in ob if k.startswith("object_")]
            info[vid] = (max(ends) if ends else None, len(objs), max(ids) if ids else -1)
    return info


def stats(values):
    a = np.asarray([v for v in values if v is not None], dtype=float)
    if a.size == 0:
        return "–"
    return (f"mean {a.mean():.1f} ± {a.std():.1f} | p50 {np.percentile(a, 50):.1f} | "
            f"p90 {np.percentile(a, 90):.1f} | max {a.max():.1f}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--splits", nargs="*", default=SPLITS)
    ap.add_argument("--pvd_files", type=int, default=40, help="PVD mask shards to read (of 550)")
    ap.add_argument("--out", default="notes/phase1_durations.md")
    args = ap.parse_args()

    out = ["# Phase 1.4: video length vs. relation spans (mask metadata)", "",
           "Generated by `tools/mask_meta.py`. `frames` = frames the masks are indexed by. "
           "Duration (s) = frames / fps, only where the fps is known.", ""]
    t0 = time.time()
    for split in args.splits:
        max_files = args.pvd_files if split.endswith("pvd") else 10**9
        meta = load_meta(split, max_files).to_pydict()
        ann = annotation_info(split)
        fps = KNOWN_FPS.get(split)

        rows = []
        for vid, nf, h, w, no in zip(*(meta[c] for c in META_COLS)):
            max_end, n_ann, max_id = ann.get(vid, (None, 0, -1))
            rows.append((vid, nf, h, w, no, max_end, n_ann, max_id))
        matched = [r for r in rows if r[0] in ann]
        with_spans = [r for r in matched if r[5] is not None]

        out += [f"## {split}", "",
                f"- videos in mask files read: {len(rows)}; with annotations: {len(matched)}; "
                f"with relations: {len(with_spans)}",
                f"- frames per video: {stats([r[1] for r in rows])}",
                f"- frame size (h×w) most common: "
                f"{sorted({(r[2], r[3]) for r in rows}, key=lambda s: -sum(1 for r in rows if (r[2], r[3]) == s))[:3]}"]
        if fps:
            out.append(f"- duration at {fps} fps (s): {stats([r[1] / fps for r in rows])}")
        if with_spans:
            out.append(f"- max span end per video (s): {stats([r[5] for r in with_spans])}")
            if fps:
                # Training convention: [a, b] inclusive seconds -> the video must last >= b + 1 s.
                # Test convention (dataset card): ends at b -> must last >= b s.
                slack = 0 if split.startswith("SVG2_test") else 1
                bad = [r for r in with_spans if r[5] + slack > r[1] / fps + 1.0]
                out.append(f"- videos whose last span ends **after the video ends** (>1 s tolerance): "
                           f"{len(bad)} of {len(with_spans)}")
                for r in sorted(bad, key=lambda r: r[5] - r[1] / fps, reverse=True)[:8]:
                    out.append(f"    - `{r[0]}`: {r[1]} frames = {r[1] / fps:.1f} s, span ends at {r[5]}")
            # Without knowing the fps: if spans are seconds, frames / (end + 1) is at least the
            # real fps of that video. Values far below any real frame rate mean the spans
            # cannot be seconds.
            implied = [r[1] / (r[5] + 1) for r in with_spans]
            a = np.asarray(implied)
            out.append(f"- implied minimum fps = frames / (max span end + 1): p1 {np.percentile(a, 1):.1f} | "
                       f"p5 {np.percentile(a, 5):.1f} | p50 {np.percentile(a, 50):.1f}; "
                       f"videos below 10 fps: {int((a < 10).sum())}")
            low = sorted(with_spans, key=lambda r: r[1] / (r[5] + 1))[:5]
            out.append("    - lowest: " + ", ".join(f"`{r[0]}` {r[1]} frames, span end {r[5]}" for r in low))
        id_bad = [r for r in matched if r[7] >= r[4]]
        out.append(f"- videos whose annotated object ids do not fit in the mask file (id ≥ num_objects): "
                   f"{len(id_bad)}")
        out.append("")
        print(f"done {split} ({time.time() - t0:.0f}s)")

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"\nReport written to {args.out}")


if __name__ == "__main__":
    main()
